'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.586
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property barrel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barrel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BobbSmiling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BobbSmiling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BobbStanding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BobbStanding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DK1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DK1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Game_Over__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Game_Over (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property godmode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("godmode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hammerLeftSmasher1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hammerLeftSmasher1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hammerRightSmasher1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hammerRightSmasher1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ladder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ladder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property level1_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("level1-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioClimb2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioClimb2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioClimb3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioClimb3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftMove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftMove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioLeftMove2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioLeftMove2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightFloat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightFloat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightMove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightMove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightMove11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightMove11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marioRightMove2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioRightMove2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WIN2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WIN2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wise_fat_face() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wise_fat_face", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
